### PR TITLE
Added "Show study left time" option

### PR DESCRIPTION
**Pull request by b0r3d0m**
Added "Show study left time" option

Activated and deactivated by the corresponding check box in "Display settings"

addition_2_1
addition_2_2

### CODE REVIEW

**Comment by romovs** [comment]
Oh this is awesome!

Couple of things though,

If displayed at the bottom it will conflict with other quality options which are also displayed there. Can we move it to the top instead? It will conflict with percentage then but in that case could hide the percentage so the user will have option to see either the percentage or the time.

Is there any particular reason you setup a new thread for this? Thread context switching has big overhead and seeing as the client is rather resource hungry as it is, it would be probably better to avoid new threads unless really necessary.
Perhaps the time could be updated only when the meter value changes? Might get jumpy for long running curios, but then again you probably don't need to see the exact time anyway.

**Comment by b0r3d0m** [comment]
> Can we move it to the top instead? It will conflict with percentage then but in that case could hide the percentage so the user will have option to see either the percentage or the time.
Ok, but do we have smth like radio buttons implemented?

> Is there any particular reason you setup a new thread for this?
I just want to pass the execution back to the caller code as fast as possible.

> Perhaps the time could be updated only when the meter value changes?
Then it won't work with items which didn't get any meters info yet

**Comment by romovs** [comment]
> Ok, but do we have smth like radio buttons implemented?

Nope no radio buttons sadly.
I think it would be easier to do that just automatically depending on the item type:
If item is a curio (and the option is cheked) then show the remaining time. Else show the percentage. 

There is flag for curios btw in GItem.quality.curio

> Then it won't work with items which didn't get any meters info yet

Ah yeah that makes sense.

**Comment by b0r3d0m** [comment]
> I think it would be easier to do that just automatically depending on the item type

Maybe we should uncheck the "Display item completion as percentage" option automatically when the option "Show study left time" will be checked?

**Comment by romovs** [comment]
But what if you want to see both. Like when running smelters or whatever you usually would like to see the percentage.
If it's strictly either percentage or time then it would be very annoying to go the the settings each time to change it.

**Comment by b0r3d0m** [comment]
Yep, you're right.

Updated pull request, please look at it.

Unfortunately, I encountered a strange bug. When you have the same item (for example, Poppy Flower) in both Study menu and inventory then the one from inventory won't have "Study time left" info. Do you have any ideas why?

**Comment by b0r3d0m** [comment]
It seems like the last (?) item in inventory doesn't count as a WItem, because now I have the following situation:

bug

So it doesn't related to the "same-item-as-in-study-menu" situation at all

**Comment by romovs** [comment]
Awesome thanks!
I already closed the upcoming release 1.17 so this will go into the next version.

> It seems like the last (?) item in inventory doesn't count as a WItem, because now I have the following situation:

Hmm I don't see anything abnormal which might cause that. Will need to fire up a debugger for that.



I still feel though that the approach with threads needs to be changed somehow. New thread for each item is really not a good idea.
I'll try to go over it tomorrow to see what can be done. Can't think straight atm...

**Comment by b0r3d0m** [comment]
It seems that getting study time in the updatetimelefttex method can go into infinite loop -- fixed now

But it doesn't related to the previous problem anyway

> I already closed the upcoming release 1.17 so this will go into the next version

Yeah, I see, thanks for credits btw

> I'll try to go over it tomorrow to see what can be done

Will wait for it

**Comment by b0r3d0m** [comment]
Wow, it looks really strange for me now

Add the following code to the GItem's constructor:

    public GItem(Indir<Resource> res, Message sdt) {
        this.res = res;
        this.sdt = new MessageBuf(sdt);

        new Thread(new Runnable() {
            public void run() {
                while (true) {
                    try {
                        Curiosity ci = ItemInfo.find(Curiosity.class, info());
                        if (ci == null) {
                            System.out.println(Thread.currentThread().getId() + ": ci == null");
                        }

                        String name = ItemInfo.find(ItemInfo.Name.class, info()).str.text;
                        System.out.println(Thread.currentThread().getId() + ": " + name);

                        break;
                    } catch (Exception ex) {
                        try {
                            Thread.sleep(100);
                        } catch (InterruptedException ie) {
                            return;
                        }
                    }
                }
            }
        }).start();
    }

With all items shown in the attached screenshot I've got the following output:

41: ci == null
47: ci == null
48: ci == null
47: Lake Gate
48: Forest Gate
58: Ladybug
60: Lady's Mantle
57: Emerald Dragonfly
62: Thorny Thistle
41: River Pearl
61: Uncommon Snapdragon
63: Feather Trinket
59: Poppy Flower
50: ci == null
50: Stone Axe
43: Emerald Dragonfly
45: Mirkwood Offering
44: Emerald Dragonfly
49: ci == null
53: ci == null
53: Nettle Shirt
42: Ladybug
54: ci == null
51: ci == null
52: ci == null
56: ci == null
46: Mirkwood Offering
56: Leather Backpack
52: Nettle Pants
51: Bunny Slippers
54: Sprucecap
49: Slave Key
55: ci == null
55: Bucket

Note that the thread with ID == 41 (related to the River Pearl) said that it isn't curiosity at all

screen

**Comment by b0r3d0m** [comment]
It looks like you need to get the client some time to think about it, because the following code with Thread.sleep(1000) added works as expected:

                while (true) {
                    try {
                        Thread.sleep(1000);

                        Curiosity ci = ItemInfo.find(Curiosity.class, info());
                        if (ci == null) {
                            System.out.println(Thread.currentThread().getId() + ": ci == null");
                        }
                    // ...
                }

**Comment by b0r3d0m** [comment]
Ah, it looks like we need to wait for the "tt" message before calling "info" method

**Comment by b0r3d0m** [comment]
Fixed (I hope so), please look at it

**Comment by b0r3d0m** [comment]
Also, regarding our "too-many-threads" issue -- we can create a thread pool with fixed size and add any tasks related to "Study time" getting to it

**Comment by romovs** [comment]
Ok I am hard-coding the study times instead of pulling them from wiki each time, that should also solve the threading issue.
Otherwise it just way too laggy on low end machines when you open a cupboard.

**Comment by b0r3d0m** [comment]
But this way you'll have to update the client each time when information about study times will update on wiki. What's wrong with the thread pool btw?

**Comment by b0r3d0m** [comment]
Ok, there's another way -- we can start single thread at the game's launch that will gather info about all curiosities listed here (http://ringofbrodgar.com/wiki/Curiosity) and save its study times via Preferences class. Then we will just get this value and update it on the next game's launch to ensure that all information is up-to-date.

**Comment by romovs** [comment]
Yep anything which doesn't involve having 64+ threads running simultaneously each time is good. :)

**Comment by b0r3d0m** [comment]
I agree.

We need to choose the best option then.

What do you think is the best option in our case -- fixed thread pool or just single thread on startup?

**Comment by romovs** [comment]
Single thread on startup is preferable imo

**Comment by b0r3d0m** [comment]
Ok, I'll make the required changes and update this pull request then

**Comment by b0r3d0m** [comment]
Ah, I don't think that we can avoid additional threads that easy.

I just noticed that we can't call the following code when GItem receives the "meter" message in its uimsg method:

    private String getname() {
        Runnable waitsometime = new Runnable() {
            public void run() {
                try {
                    Thread.sleep(100);
                } catch (InterruptedException ie) {
                    // NOP
                }
            }
        };

        while (true) {
            try {
                if (rawinfo == null) {
                    waitsometime.run();
                    continue;
                }

                return ItemInfo.find(ItemInfo.Name.class, info()).str.text;
            } catch (Exception ex) {
                waitsometime.run();
            }
        }
    }

because it leads to infinite loop with exception "Still waiting for sprite to be constructed".

But obviously we need the name of the item to update the "study left time" info accordingly.

**Comment by romovs** [comment]
Can't that be done in the drawing routine?

Something like:
You keep Tex of the "time string" and the current meter value inside GItem and whenever uimsg with new meter is received - set Tex to null (this just to notify the drawing routine that it needs to render new time string.)

Then in the drawing routine:
- if Tex is null 
  - try getting the item name. if sprite hasn't been constructed yet - do nothing
  - else if we got the name, store it in GItem for later use and render the Tex string and store it as well.
- else if Tex is not null - then everything is fine we just display the already rendered string.

But frankly if curio matching was done based on resource basename instead of tooltip sprite it would have solved all the problems with this. It's not like they are going to create new curios each month.

**Comment by b0r3d0m** [comment]
Thanks a lot for the suggestion.

Made a new pull request, please look at it.

**Comment by romovs** [comment]
Thanks!
Merged locally. Will try to to test it early next week and merge back to master.

**Pull request merged**
