### PR TITLE
Added possibility to name objects

### PR DESCRIPTION
**Pull request by b0r3d0m**
obj_names

### CODE REVIEW

**Comment by b0r3d0m** [comment]
It seems like objects' IDs do change over time

**Comment by puruscor** [comment]
Object id's do change every time server restarts im pretty sure.

**Comment by romovs** [comment]
Yeah, unfortunately, there is no reliable way to recognize objects across map unloads and server restarts.

**Comment by Inlife** [comment]
this can be achieved in other ways: for example unattach text from object and store positions for this 2d texts in 3d coordinates of world, and display them accordingly.

**Comment by puruscor** [comment]
Way to recognize house that player is in would still be required.

**Comment by Inlife** [comment]
@puruscor house could be identified by items, that are standing here. 
For example: hashed map of all positions of cupboards + tables + chairs + etc.
I think that house hash record will be unique for one local player with probability like 3/4.

plus that record can be upgraded with previous house enter event, returning door location on previous step, or smth like this. :3

**Pull request closed without merging**
